
version: '3'

services:
 pwtr:
   user: $UID:$GID
   image:
      sam_pwa
   ports:
     - "8000:8000"
   volumes:
     - ./pwtr:/pwtr:Z
   stdin_open: true
   tty: true
   command: >
     sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runsslserver 0.0.0.0:8000"
